# Generated by Django 4.2 on 2023-08-06 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('clothing', 'Clothing'), ('eletronics', 'Eletronics'), ('books', 'Books'), ('shoes', 'Shoes'), ('toy_games', 'Toy & Games'), ('beauty_personal', 'Beauty & Personal'), ('jewelry_accessories', 'Jewelry & Accessories')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('cover', models.ImageField(upload_to='imgs/products_covers/')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
        migrations.CreateModel(
            name='BookProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('author', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50, null=True)),
                ('genre', models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-Fiction'), ('romance', 'Romance'), ('mystery_thriller', 'Mystery & Thriller'), ('science_fiction', 'Science Fiction'), ('fantasy', 'Fantasy'), ('biography', 'Biography'), ('self_help', 'Self-Help'), ('history', 'History'), ('travel', 'Travel'), ('cooking', 'Cooking'), ('poetry', 'Poetry'), ('graphic_novels', 'Graphic Novels'), ('children', 'Children'), ('young_adult', 'Young Adult'), ('classic', 'Classic'), ('horror', 'Horror')], max_length=30, null=True)),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='ClothingProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('brand', models.CharField(max_length=100)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('color', models.CharField(blank=True, max_length=35, null=True)),
            ],
            bases=('store.product',),
        ),
        migrations.CreateModel(
            name='EletronicProduct',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='store.product')),
                ('brand', models.CharField(max_length=50)),
            ],
            bases=('store.product',),
        ),
    ]
